# Generated by Django 5.2 on 2025-11-09 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="storage",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="address",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="city",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="costumer_name",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="sales",
            name="order",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale",
                to="application.orders",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("feldolgozás_alatt", "Feldolgozás alatt"),
                    ("kiszállítva", "Kiszállítva"),
                    ("törölve", "Törölve"),
                ],
                default="feldolgozás_alatt",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="application.products"
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="selling_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
                ("storage", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="application.orders",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.products",
                    ),
                ),
            ],
        ),
    ]
