# Generated by Django 5.1.2 on 2025-11-11 21:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_orders_color_remove_orders_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='memory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='specs',
            name='storage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
